"""Tool: delete a custom KiCad footprint — the reverse of create_footprint.

Deletes a .kicad_mod from the writable envil footprint library, removes the
now-empty ``.pretty`` folder, unregisters it from the fp-lib-table, optionally
clears the linked symbol's Footprint property, and refreshes the footprint
index cache. Stock KiCad footprints (outside the envil library) are never
touched.
"""
from __future__ import annotations

import json
from typing import Any

from claude_agent_sdk import tool

from ..kicad.create_footprint import delete_footprint as _delete_footprint


@tool(
    name="delete_footprint",
    description=(
        "Delete a custom KiCad PCB footprint (.kicad_mod) — the reverse of "
        "create_footprint. Use this when the user wants to remove a footprint "
        "they created.\n\n"
        "Only footprints in the writable envil footprint library "
        "(<fp_lib_dir>/<nick>.pretty) can be deleted; stock KiCad footprints are "
        "never touched. If the delete empties the '.pretty' folder, the folder "
        "is removed and the library is unregistered from the fp-lib-table. The "
        "footprint index cache is refreshed so the part stops resolving.\n\n"
        "SAFETY: a footprint not generated by envil (no 'envil-fp-gen' tag) is "
        "refused unless force=true.\n\n"
        "Args:\n"
        "  fp_ref: 'FpLibNick:FpName' to delete (required, e.g. 'Custom:BQ76952').\n"
        "  unlink_symbol: optional symbol lib_id ('LibNick:PartName') whose "
        "Footprint property should be cleared (undo the create_footprint link).\n"
        "  unregister_if_empty: bool — remove the library from the fp-lib-table "
        "when the delete empties its .pretty folder (default true).\n"
        "  force: bool — delete even a footprint not generated by envil "
        "(default false).\n\n"
        "Returns JSON: {ok, fp_ref, deleted, library_removed, unregister, "
        "symbol_unlinked} or {ok:false, error}."
    ),
    input_schema={
        "fp_ref": str,
        "unlink_symbol": str,
        "unregister_if_empty": bool,
        "force": bool,
    },
)
async def delete_footprint(args: dict[str, Any]) -> dict[str, Any]:
    fp_ref = str(args.get("fp_ref", "")).strip()
    if not fp_ref:
        return {
            "content": [{"type": "text", "text": "ERROR: fp_ref is required."}],
            "is_error": True,
        }
    unlink_symbol = str(args.get("unlink_symbol", "")).strip()
    unregister_if_empty = bool(args.get("unregister_if_empty", True))
    force = bool(args.get("force", False))

    try:
        result = _delete_footprint(
            fp_ref,
            unlink_symbol=unlink_symbol,
            unregister_if_empty=unregister_if_empty,
            force=force,
        )
    except Exception as exc:
        return {
            "content": [{"type": "text",
                         "text": f"ERROR: {type(exc).__name__}: {exc}"}],
            "is_error": True,
        }

    if not result.get("ok"):
        return {
            "content": [{"type": "text",
                         "text": f"ERROR: {result.get('error', 'unknown')}"}],
            "is_error": True,
        }

    # Refresh the footprint index caches (built in tools.create_symbol) so a
    # subsequent footprint lookup no longer sees the deleted .kicad_mod.
    try:
        from .create_symbol import _all_footprints, _fp_pad_count
        _all_footprints.cache_clear()
        _fp_pad_count.cache_clear()
    except Exception:
        pass

    return {
        "content": [{"type": "text", "text": json.dumps(result, indent=2)}],
        "is_error": False,
    }
