"""Tool: one-call documentation pack. Produces a `docs/` folder next
to the .kicad_sch containing everything needed to share / hand over /
publish a project:

  - <name>.pdf            schematic PDF (kicad-cli sch export pdf)
  - <name>.svg            schematic SVG (already auto-generated by build)
  - <name>-3d-top.png     PCB top view
  - <name>-3d-bottom.png  PCB bottom view
  - <name>-bom.csv        Bill of Materials
  - README.md             auto-generated project summary

Universal — works on any .kicad_sch. All toggles JSON-driven in
`layout_config.json:export_docs` per feedback_no_hardcode_json_config.
"""
from __future__ import annotations

import importlib
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List

from claude_agent_sdk import tool


def _load_cfg() -> Dict[str, Any]:
    try:
        from ..intent.engine import _load_layout_config
        return _load_layout_config().get("export_docs", {}) or {}
    except Exception:
        return {}


def _kicad_cli(cfg: Dict[str, Any]) -> str:
    if cfg.get("kicad_cli_command"):
        return str(cfg["kicad_cli_command"])
    try:
        from ..intent.engine import _load_layout_config
        return str(_load_layout_config().get("erc_check", {}).get(
            "kicad_cli_command", "kicad-cli"))
    except Exception:
        return "kicad-cli"


def _export_pdf(cli: str, sch: Path, pdf: Path, timeout: int,
                 bw: bool = False) -> bool:
    cmd = [cli, "sch", "export", "pdf",
            "--output", str(pdf),
            "--exclude-drawing-sheet" if False else "--exclude-pdf-property-popups",
            str(sch)]
    if bw:
        cmd.insert(-1, "--black-and-white")
    try:
        r = subprocess.run(cmd, capture_output=True, text=True,
                            timeout=timeout)
        return r.returncode == 0 and pdf.exists()
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return False


def _render_readme(name: str, files: Dict[str, str],
                    extras: Dict[str, Any]) -> str:
    """Compose a project README from the artefacts produced. Keeps the
    bullet ordering predictable so the same input produces the same
    output (no per-call randomness)."""
    lines = [
        f"# {name}",
        "",
        f"Generated by Envil on {extras.get('date', '')}.",
        "",
        "## Files",
        "",
    ]
    titles = {
        "schematic_pdf":  "schematic PDF",
        "schematic_svg":  "schematic SVG",
        "pcb_top":        "PCB 3D — top",
        "pcb_bottom":     "PCB 3D — bottom",
        "bom_csv":        "Bill of Materials",
        "kicad_sch":      "KiCad schematic",
        "kicad_pcb":      "KiCad PCB",
        "kicad_pro":      "KiCad project",
        "gerbers_zip":    "Gerbers ZIP (fab handoff)",
    }
    for key in ("schematic_pdf", "schematic_svg", "pcb_top", "pcb_bottom",
                 "bom_csv", "kicad_sch", "kicad_pcb", "kicad_pro",
                 "gerbers_zip"):
        path = files.get(key)
        if not path:
            continue
        rel = Path(path).name
        lines.append(f"- **{titles.get(key, key)}**: [`{rel}`](./{rel})")
    lines.append("")
    if extras.get("component_count"):
        lines.append(f"**Component count:** {extras['component_count']}")
        lines.append("")
    if extras.get("notes"):
        lines.append("## Notes")
        lines.append("")
        lines.append(extras["notes"])
        lines.append("")
    lines.append("---")
    lines.append("Generated by `export_docs`.")
    return "\n".join(lines)


@tool(
    name="export_docs",
    description=(
        "One-call documentation pack. Produces a docs/ folder next to "
        "the schematic with: schematic PDF + SVG, PCB 3D top+bottom "
        "PNGs, BOM CSV, and an auto-generated README.md. Universal — "
        "works on any .kicad_sch. Use when the user asks: 'package "
        "the docs', 'share the project', 'export for handover', "
        "'make the GitHub release', 'documentation pannu'.\n"
        "Args:\n"
        '  {"sch_path": "C:/.../proj.kicad_sch"}     # required\n'
        '  {"sch_path": "...", "bw": true}           # black & white PDF\n'
        '  {"sch_path": "...", "include_3d": false}  # skip PCB renders\n'
        '  {"sch_path": "...", "include_bom": false} # skip BOM step\n'
    ),
    input_schema={"sch_path": str},
)
async def export_docs(args: dict[str, Any]) -> dict[str, Any]:
    sch_path = Path(str(args.get("sch_path", "")).strip()).expanduser()
    if not sch_path.exists():
        return {"content": [{"type": "text",
                              "text": f"ERROR: .kicad_sch not found: {sch_path}"}],
                 "is_error": True}
    if sch_path.suffix.lower() != ".kicad_sch":
        return {"content": [{"type": "text",
                              "text": f"ERROR: expected .kicad_sch, got {sch_path.suffix}"}],
                 "is_error": True}

    cfg = _load_cfg()
    if not cfg.get("enabled", True):
        return {"content": [{"type": "text",
                              "text": "export_docs disabled in layout_config.json"}],
                 "is_error": True}

    cli = _kicad_cli(cfg)
    timeout = int(cfg.get("timeout_seconds", 90))
    bw = bool(args.get("bw", cfg.get("bw", False)))
    include_3d = bool(args.get("include_3d", cfg.get("include_3d", True)))
    include_bom = bool(args.get("include_bom", cfg.get("include_bom", True)))

    docs_dir = sch_path.parent / cfg.get("dirname", "docs")
    docs_dir.mkdir(parents=True, exist_ok=True)

    files: Dict[str, str] = {}
    summary_lines: List[str] = []

    # 1. Schematic PDF
    pdf_path = docs_dir / (sch_path.stem + ".pdf")
    if _export_pdf(cli, sch_path, pdf_path, timeout, bw=bw):
        files["schematic_pdf"] = str(pdf_path)
        summary_lines.append(f"  ✓ schematic PDF: {pdf_path.name}")
    else:
        summary_lines.append("  ✗ schematic PDF failed")

    # 2. Schematic SVG — copy the engine-generated one if present
    svg_src = sch_path.with_suffix(".svg")
    if svg_src.exists():
        svg_dst = docs_dir / svg_src.name
        try:
            shutil.copy(svg_src, svg_dst)
            files["schematic_svg"] = str(svg_dst)
            summary_lines.append(f"  ✓ schematic SVG: {svg_dst.name}")
        except OSError:
            summary_lines.append("  ✗ schematic SVG copy failed")
    else:
        # Regenerate via engine helper
        try:
            from ..intent.engine import _export_preview_svg
            svg = _export_preview_svg(sch_path, out_dir=docs_dir)
            if svg and svg.exists():
                files["schematic_svg"] = str(svg)
                summary_lines.append(f"  ✓ schematic SVG: {svg.name}")
            else:
                summary_lines.append("  - schematic SVG skipped")
        except Exception:
            summary_lines.append("  - schematic SVG skipped")

    # 3. PCB 3D renders
    pcb_path = sch_path.with_suffix(".kicad_pcb")
    if include_3d and pcb_path.exists():
        try:
            R3D = importlib.import_module("envil_agent.tools.render_pcb_3d")
            r = await R3D.render_pcb_3d.handler({"pcb_path": str(pcb_path)})
            for img in (r.get("images") or []):
                src = Path(img)
                dst = docs_dir / src.name
                try:
                    if src.resolve() != dst.resolve():
                        shutil.copy(src, dst)
                except OSError:
                    pass
                if "top" in src.name.lower():
                    files["pcb_top"] = str(dst)
                elif "bottom" in src.name.lower():
                    files["pcb_bottom"] = str(dst)
            if r.get("images"):
                summary_lines.append(f"  ✓ PCB 3D: {len(r.get('images', []))} image(s)")
            else:
                summary_lines.append("  - PCB 3D skipped (empty board)")
        except Exception as exc:
            summary_lines.append(f"  ✗ PCB 3D error: {exc}")
    elif include_3d:
        summary_lines.append("  - PCB 3D skipped (no .kicad_pcb)")

    # 4. BOM CSV
    if include_bom:
        try:
            BOM = importlib.import_module("envil_agent.tools.export_bom")
            bom_out = docs_dir / (sch_path.stem + "-bom.csv")
            r = await BOM.export_bom.handler({
                "sch_path": str(sch_path),
                "output": str(bom_out),
                "preset": cfg.get("bom_preset", "altium"),
            })
            if bom_out.exists():
                files["bom_csv"] = str(bom_out)
                summary_lines.append(f"  ✓ BOM CSV: {bom_out.name} ({r.get('rows', '?')} parts)")
            else:
                summary_lines.append("  ✗ BOM export failed")
        except Exception as exc:
            summary_lines.append(f"  ✗ BOM error: {exc}")

    # 5. Pointers (not copies) to the KiCad project files + Gerbers ZIP
    for k, p in {
        "kicad_sch": sch_path,
        "kicad_pcb": sch_path.with_suffix(".kicad_pcb"),
        "kicad_pro": sch_path.with_suffix(".kicad_pro"),
        "gerbers_zip": sch_path.with_name(sch_path.stem + "-gerbers.zip"),
    }.items():
        if p.exists():
            files[k] = str(p)

    # 6. Component count for the README
    component_count = 0
    try:
        READ = importlib.import_module("envil_agent.tools.read_schematic")
        rd = await READ.read_schematic.handler({"path": str(sch_path)})
        import json as _json
        component_count = len(_json.loads(rd["content"][0]["text"]).get(
            "components", []))
    except Exception:
        pass

    # 7. README
    import time
    readme_path = docs_dir / "README.md"
    try:
        readme_path.write_text(_render_readme(
            sch_path.stem,
            files,
            {"date": time.strftime("%Y-%m-%d"),
             "component_count": component_count,
             "notes": cfg.get("readme_notes", "")},
        ), encoding="utf-8")
        files["readme"] = str(readme_path)
        summary_lines.append(f"  ✓ README.md")
    except OSError:
        summary_lines.append("  ✗ README failed")

    header = f"Docs pack -> {docs_dir}"
    text = header + "\n" + "\n".join(summary_lines)
    text += f"\n\nFiles in pack: {len(files)}"

    return {
        "content": [{"type": "text", "text": text}],
        "ok": "schematic_pdf" in files,
        "docs_dir": str(docs_dir),
        "files": files,
    }
