"""Bus IR --- declarative bus definitions for the architect.

Buses let the architect declare `D[0..7]` once instead of emitting eight
separate `D0..D7` nets. The engine then renders one bus line with bus
entries breaking out to the individual signals, matching IEEE 315 6.5 /
KiCad User Manual 6.3.

Wiring rule R9 from `WIRING_RULES.md`. Engine integration is a follow-up
(needs the `_emit_local_label` callsite in `intent/engine.py` to suppress
per-net labels for bus members and substitute bus entries); this module
ships the IR + detection helper so the architect can already declare
buses, and validate_ir can already validate them.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List


_BUS_RANGE_RE = re.compile(r"^([A-Za-z_]+)\[(\d+)\.\.(\d+)\]$")
_MEMBER_RE = re.compile(r"^([A-Za-z_]+)(\d+)$")


@dataclass
class BusDef:
    """A bus declaration.

    `name`: the bus label as it should render in the schematic
            (e.g. `DATA[0..7]`). The architect may emit either the
            explicit range form `DATA[0..7]` or a bare prefix `DATA`
            and let the engine compute the range from `members`.
    `members`: the individual net names that belong to the bus
               (e.g. `["DATA0","DATA1",...,"DATA7"]`). The engine
               expects each member to be a separately-declared
               `IRNet` --- this list is the pointer.
    `width`: convenience field; redundant with `len(members)`, kept
             so consumers can sanity-check IRs that the architect
             generated by template.
    """
    name: str
    members: List[str] = field(default_factory=list)
    width: int = 0

    @classmethod
    def from_dict(cls, d: dict) -> "BusDef":
        return cls(
            name=str(d.get("name", "")),
            members=list(d.get("members", [])),
            width=int(d.get("width", 0) or len(d.get("members", []))),
        )

    def canonical_name(self) -> str:
        """Return the `<prefix>[lo..hi]` form. When the architect emitted
        a bare prefix, derive the range from members."""
        m = _BUS_RANGE_RE.match(self.name)
        if m:
            return self.name
        idxs: List[int] = []
        for member in self.members:
            mm = _MEMBER_RE.match(member)
            if mm:
                try:
                    idxs.append(int(mm.group(2)))
                except ValueError:
                    pass
        if not idxs:
            return self.name
        return f"{self.name}[{min(idxs)}..{max(idxs)}]"
